version: '3'
services:
  postgres:
    image: postgres:13.0-alpine
    expose:
      - "5432"
    ports:
      - "127.0.0.1:51000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "127.0.0.1:51001:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
