# Generated by Django 4.1.7 on 2023-03-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-created',), 'verbose_name': 'история активации кода', 'verbose_name_plural': 'история активаций кодов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productpromocode',
            options={'verbose_name': 'привязанный продукт', 'verbose_name_plural': 'привязанные продукты'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('-created',), 'verbose_name': 'промокод', 'verbose_name_plural': 'промокоды'},
        ),
        migrations.AlterField(
            model_name='history',
            name='applied_user_id',
            field=models.UUIDField(null=True, verbose_name='Код применен пользователем (UUID id)'),
        ),
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='history',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Размер примененной скидки в валюте счета'),
        ),
        migrations.AlterField(
            model_name='history',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='productpromocode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='productpromocode',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='productpromocode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='activates_left',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для автоподстановки', verbose_name='Количество оставшихся активаций'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AddConstraint(
            model_name='productpromocode',
            constraint=models.UniqueConstraint(fields=('product', 'promo_code'), name='UniqProductPerPromo'),
        ),
    ]
