# Generated by Django 4.1.7 on 2023-03-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promo', '0002_alter_history_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='applied_user_id',
            field=models.UUIDField(default=0, verbose_name='Код применен пользователем (UUID id)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='billing_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация от сервиса оплаты'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код действителен до'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код действителен с'),
        ),
    ]
