# Generated by Django 4.1.7 on 2023-03-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_history_applied_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование продукта'),
        ),
    ]
