# Generated by Django 4.1.7 on 2023-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_product_description_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
