# Generated by Django 4.1.7 on 2023-03-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_bulkpromocreate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpromocreate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Размер скидки/фикса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='discount_type',
            field=models.CharField(choices=[('fixed_price', 'фиксированная цена'), ('percentage_discount', 'скидка в процентах'), ('fixed_discount', 'фиксироанная скидка')], default=0, max_length=30, verbose_name='Тип лояльности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код действителен до'),
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='minimal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Минимальная сумма чека для применения скидки'),
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promos_bulk', through='promo.ProductPromoCode', to='promo.product', verbose_name='Код привязан к продуктам'),
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код действителен с'),
        ),
        migrations.AddField(
            model_name='bulkpromocreate',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpromocode',
            name='bulk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promo.bulkpromocreate'),
        ),
        migrations.AlterField(
            model_name='productpromocode',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promo.promocode'),
        ),
        migrations.AddConstraint(
            model_name='productpromocode',
            constraint=models.UniqueConstraint(fields=('product', 'bulk'), name='UniqProductPerBulk'),
        ),
        migrations.AddConstraint(
            model_name='productpromocode',
            constraint=models.CheckConstraint(check=models.Q(('promo_code__isnull', False), ('bulk__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
